### ISSUE TITLE
com.sun.net.httpserver should not be forbidden

### ISSUE THREAD

**Issue by javanna** [policeman-tools/forbidden-apis#103]
In some elasticsearch integration tests we want to start an http server to send requests to. The easiest is to use `com.sun.net.httpserver.HttpServer` but it turns out that the jdk-non-portable bundled signature forbids its usage based on heuristic checks. We are discussing this with Simon and it seems like it should not be forbidden, the `HttpServer` class is also annotated [@Exported](https://docs.oracle.com/javase/8/docs/jdk/api/javac/tree/jdk/Exported.html) which seems ok. Would it be possible to ignore that whole package as part as the jdk-non-portable checks or should this really be forbidden?

Here is the related discussion on the elasticsearch project: https://github.com/elastic/elasticsearch/pull/18735#discussion_r66576472 .

**Comment by uschindler** [comment]
This is not an issue, as the following: The Webserver classes are "non portable". They are exported by the Oracle JDK, but they are still not part of any Java standard. So non-Oracle JDKs may not have it (e.g., IBM J9). This is similar to the HotspotMXBean, because Hotspot is Oracle/OpenJDK and not part of Java standard.

This issue cannot be fixed, as the algorithm cannot "exclude" somehow com.sun.net.httpserver. `jdk-non-portable` is not a signatures file, the checks are done algorithmically: Every class that is not part of the Java Standard's packages (this does not include com.sun.net.httpserver)  and is part of the runtime (comes from rt.jar or is part of "java.*" or "jdk.*" modules) if forbidden.

If you just want to forbid stuff that breaks with Java 9 by Oracle, you can use another bundled signatures: "jdk-internal". This signatures file is based on the packages that Oracle officially blacklists.

**Comment by uschindler** [comment]
FYI: This is `jdk-internal`: https://github.com/policeman-tools/forbidden-apis/blob/master/src/main/resources/de/thetaphi/forbiddenapis/signatures/jdk-internal-1.8.txt
