### ISSUE TITLE
Submit Gradle plugin to plugins.gradle.org

### ISSUE THREAD

**Issue by sdavids** [policeman-tools/forbidden-apis#107]
Please submit your Gradle plugin to the Gradle Plugin Portal:

https://plugins.gradle.org/docs/submit

It would simplify Gradle build files.

Instead of:

```
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'de.thetaphi:forbiddenapis:2.2'
  }
}

apply plugin: 'de.thetaphi.forbiddenapis'
```

One would only need:

`plugins {
    id "de.thetaphi.forbiddenapis" version "2.2"
}`

See: https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block

**Comment by uschindler** [comment]
Hi,

I can look into this, but as forbidden-apis is not a Gradle project, it cannot easily use the plugin publishing API (no connector from Apache Ant). No idea how to publish it there.

For several reasons, forbiddenapis cannot be built with Gradle at the moment (e.g., `gradleApi()` classpath pollution is a blocker, which should have been fixed in newest Gradle version).

BTW: forbiddenapis is also available on `jcenter()` repo, so Gradle should find it by default.

**Comment by uschindler** [comment]
Wht I can do at least is providing the plugin marker artifact: https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers

Publishing in Gradle's repository is impossible. Using the marker artifact, it would reduce the above code to:

```gradle
pluginRepositories {
  maven {
    mavenCentral()
  }
}

plugins { id "de.thetaphi.forbiddenapis" version "2.2" }
```

**Comment by uschindler** [comment]
Hi,
thanks Sebastian. I think I found a solution how to publish the plugin to the Gradle Plugin portal. Actually that is not easy, because by default it only works for plugins that were created by a gradle build, so it tries to run the tasks 'compile*', 'jar', 'javadocs',... and then also relies on the artifact name.
The trick was to disable all the basic tasks of the java plugin that generate the artifacts (plugin jar, source jar, javadocs) and replace by a copy task, that uses a separate configuration to download the real plugin artifacts from Maven Central, put them at the same place like the jarred artifacts of the disabled tasks and then publish those using the plugin. This was not so easy to figure out, as there is no documentation about the plugin internals nor any source code available. To me, the Gradle Plugin Portal looks like a not very open source friendly blackbox.

The plugin is waiting for approval and I need them to delete it again (i did some test uploads, but there are now broken artifacts in the plugin portal).

The current state, including the used build.gradle file (just for this download from Maven push to Gradle one) can be found in their forum: https://discuss.gradle.org/t/please-remove-test-upload-of-plugin-which-is-not-yet-approved-anyways/28456

Once this is all sorted out, I will push all versions since 2.0 also to the Gradle Plugin portal.

**Comment by uschindler** [comment]
Here is the gist with my "publish hack": https://gist.github.com/uschindler/8af468efe73aaded3d8e25f265e5e192

**Comment by uschindler** [comment]
The 2.x series of the plugin (1.x has no Gradle support) were released through the plugin portal. I did a quick test, all seems fine: https://plugins.gradle.org/plugin/de.thetaphi.forbiddenapis

Could you check it, because I can delete and re-upload them for up to 7 days.

**Comment by uschindler** [comment]
This is a completely different issue and has noting to do with this one. Which Gradle version? Can you post the full stacktrace in a new issue?

**Comment by uschindler** [comment]
In my own check it works, by the way (Gradle 3.3 and Gradle 4.3).

**Comment by uschindler** [comment]
This looks like an issue with order of initialization. The new plugin mechanism initializes the forbidden plugin first, and this causes the error message.

The reason for this is: The plugin does not explicitly load the java plugin, instead it just looks if it's there. Other plugin do it in the same way.

The better way to handle this would be to load the JavaBasePlugin first using apply(). This cannot be fixed for existing versions out there. But this is a new issue, so I'd open a new one.

BTW, sometimes it works, depending on which other plugin you actually have in your gradle file. It looks like Gradle initializes 3rd party plugins first (I have no idea why).
