### ISSUE TITLE
jdk-internal-1.8 inadvertently blocks classes from other, non-JDK, jars

### ISSUE THREAD

**Issue by trejkaz** [policeman-tools/forbidden-apis#113]
jdk-internal-1.8 has the following pattern:

```
com.sun.media.**
```

com.sun.media.imageioimpl.plugins.tiff is present in a non-JDK jar, jai_imageio-1.1.jar, so this pattern inadvertently excludes it as well. (Now, this class in particular may well be considered internal anyway, since it's imageioimpl... but I don't think it's "JDK internal", since it isn't JDK!)

**Comment by uschindler** [comment]
Hi,

there are 2 different signatures: "jdk-non-portable" (which uses heuristics) and will not trigger on the above packages. The reason is that it checks for classes part of runtime, but not officially documented as part of core JDK Javadocs. This excludes all of the above classes, too, but with a small difference: It only applies to classes coming from below Java/home or are in any module (Java 9) starting with "java.*" or "jdk.*".

The "jdk-internal" signatures file is just a hardcoded list, but dynamically prepared from the Security Manager settings. The above classes are threated with special care by the security manager. See <https://github.com/policeman-tools/forbidden-apis/blob/master/src/main/resources/de/thetaphi/forbiddenapis/signatures/jdk-internal-1.8.txt> for more info (comment).

I'd suggest to use "jdk-non-portable", the "jdk-internal" stuff was only added for @rmuir's paranoia :-)

**Comment by trejkaz** [comment]
I guess I'll have to delay adding the rule to our build for the time being. jdk-non-portable reports violations, which is true, so I wanted to make a file which was jdk-non-portable minus the few things we're already abusing. But it turned out jdk-non-portable wasn't a hard-coded list, of course. So for now, we'll probably just cross fingers that nobody adds any new ones before we manage to remove the rest.

Problem is that not all of the things which jdeps complains about have obvious replacements. It only offers suggested replacements for about 1/3 of the issues it reports... and some of the rest of the stuff I couldn't even find replacements for after hunting around on Google. So it's a super slow process. :(

**Comment by uschindler** [comment]
Maybe just copy the jdk-internal list and remove some stuff until you solved the problems?

**Comment by uschindler** [comment]
The `jdk-internal` lists are static and of course affect non-jdk classes. This is why there is `jdk-non-portable`.
