### ISSUE TITLE
Allow to use plugin without having the tasks be part of "check"

### ISSUE THREAD

**Issue by centic9** [policeman-tools/forbidden-apis#114]
We are in the process of adding api checks to a large project. We would like to initially have it not be part of the "check" task as it currently has quite an impact on build-time and local dev usually invoke "check" before checkin, so we would like to add it in a separate CI job initially and then try to roll it out to the developer builds.

I saw that the plugin hardcoded assigns itself to the "check" target. I tried to remove that dependency in our local build-file, but that did not work. 

Is it possible to add a flag which does not add the forbiddenApi tasks to "check"?

**Comment by uschindler** [comment]
Are you talking about Gradle? I know from the Elasticsearch people, that you can easily remove it from the check.

**Comment by uschindler** [comment]
The official way to disable it is described here: https://discuss.gradle.org/t/remove-task-dependency/18493/2

What you can do is (Elasticsearch does this):
- Add a separate CI builds task (different to "check")
- Let this one depend on forbiddenapis
- Disable the default fobiddenapis with enabled = false

This is not different to Maven, where you also cannot change the way how plugins depend on each other. If you need full flexibility, use Ant :-)

**Comment by centic9** [comment]
Thanks a lot for the pointers/workaround, that should do the trick!

**Comment by centic9** [comment]
For the record, I ended up using the following to have the checks disabled by default and enabled if `-PenableForbiddenApiCheck` is added to the Gradle commandline:

```	// do not include this check by default for now to not cause the build to take longer
	if (!project.hasProperty('enableForbiddenApiCheck')) {
		project.tasks.getByName('forbiddenApis').enabled = false
		project.tasks.getByName('forbiddenApisMain').enabled = false
		project.tasks.getByName('forbiddenApisTest').enabled = false
	}
```

**Comment by uschindler** [comment]
Hi,

thanks for feedback. I think you will have to do the same with other "check" tasks like CheckStyle or PMD. I wonder why only forbiddenapis looks slow to you. CheckStyle or PMD are much slower and they have exactly the same problem: They are hardcoded to run under "check" by default. So thhe hack you provide here is fine, but I wonder why some developer would run "gradle check" at all, if he does not want any check.

I just tell this, because forbiddenApis is not different from any of those other "check" tasks.
