### ISSUE TITLE
Deprecation warning with Gradle 4.0-rc-1

### ISSUE THREAD

**Issue by huxi** [policeman-tools/forbidden-apis#120]
The following deprecation warning is generated with Gradle 4.0-rc-1:

```
Using a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
	at de.thetaphi.forbiddenapis.gradle.CheckForbiddenApis_Decorated.getClassesDir(Unknown Source)
```

Output above is generated with `--stacktrace` option, grepping the stacktrace elements on `thetaphi`.

**Comment by uschindler** [comment]
Thanks for the hint. Up to now I have no idea how to fix this proerly, because the current Gradle plugin compiles against version 2.3 of Gradle and I don't plan to release an update in a minor version, as this change would break it for users with all earlier Gradle versions.

I think I can fix this with the next major version of forbiddenapis, but I have no idea what the correct fix is. I'd suggest to wait for the official Gradle documentataion about this. Up to now I have not found anything about this on the net. This is just a warning and I see no urgency. It looks like many plugins are affected by this.

**Comment by uschindler** [comment]
See https://docs.gradle.org/4.0-milestone-2/release-notes.html#deprecated-apis

**Comment by trejkaz** [comment]
I saw someone on the forum talking about dodging it using reflection to call the newer method:

https://discuss.gradle.org/t/gradle-4-0-warning-what-is-this/23004/8

We're getting this in our build too, but we have so many plugins and more than half of them might be doing it, and there is no way to know because Gradle doesn't print out who called the thing.

**Comment by uschindler** [comment]
As the plugin bottoup is written in Groovy inside forbidden-apis, this should be easy to fix. I just had no time to do it up to now, but the approach is:
- change forbiddenapis to allow multiple classes dirs (currently it only allows one, but forbiddenapi's Ant allows more - for example!)
- in the plugin init script (Groovy) just use the Groovy "hasProperty()" method and then call one or the other method to get the classes dir(s) of the source set. The relevant code line is here: https://github.com/policeman-tools/forbidden-apis/blob/master/src/main/resources/de/thetaphi/forbiddenapis/gradle/plugin-init.groovy#L54

I will prepare a fix duing the summer vacation! As said before, it's no urgent :-)

**Comment by uschindler** [comment]
I added a PR #124 that fixes the warning and changes the plugin to also use the `classesDirs` property (and deprecate the old `classesDir` in the plugin).

If anybody could check this with his build, I'd be happy!

**Comment by huxi** [comment]
Could you perform a release including the fix?

**Comment by uschindler** [comment]
Is going to happen soon. I just wanted to wait for Java 9 release to update all signatures and ASM parser.

**Comment by huxi** [comment]
Makes sense.
