### ISSUE TITLE
False positives in relation to overloaded methods

### ISSUE THREAD

**Issue by leventov** [policeman-tools/forbidden-apis#132]
When some class, which is forbidden, is used in an overloading of a method, that is called in the project, forbidden-apis incorrectly reports this as a violation. For example, you could check out this commit: https://github.com/metamx/druid/commit/f670482b21aa3c05c7444a0ee523321ad7a6f6dd, then uncomment those two lines: https://github.com/metamx/druid/blob/f670482b21aa3c05c7444a0ee523321ad7a6f6dd/codestyle/druid-forbidden-apis.txt#L4-L5, and try `mvn clean compile test-compile` from the root project directory.

**Comment by uschindler** [comment]
I haven't looked at the commit/repository yet, but as far as I remember, this is wanted behaviour:
If you override a method thats forbidden, we treat that as a forbidden call if you call the overridden method, because you are just implementing the interface/API in a different way, but code is still calling a signature that's forbidden. With virtual methods the target of the call is not 100% clear at compile time, so this is IMHO correct behaviour. You can debate about it, but back in 2012 when we implemented forbiddenapis for the first time, this was a decission we took.

Could you give a short example of the setup?

**Comment by leventov** [comment]
It's not about method override, it's about overload

**Comment by uschindler** [comment]
The two lines in your forbiddenapis signatures forbid 2 classes. This means that usage of this class anywhere in your code is forbidden:
- if its a method parameter
- if you subclass / implement that interface

In the given case (the Suppliers which are functional interfaces), I'd suggest to just forbid the methods.

**Comment by uschindler** [comment]
In any case, I will checkout your project later and try to figure out what's exactly going on. Currently I am just guessing! I will come back latest on the weekend as I am on travel at the moment.

**Comment by uschindler** [comment]
OK, I analyzed the problem:
You are using Guava 17 to compile the project. ByteSource unfortunately still implements InputSupplier (which it no longer does in Guava 18). Because of the described setup above, the type ByteSource is then also disallowed to be used in code.

The anonymous class declares a constructor taking the ByteSource from the outer method. And therefor it complains, as ByteSource implements the forbidden interface. This is a corner case where it is questionable: Maybe we should only check superclasses/interfaces when calling methods not when using types. But I have no idea about side effects and other implications here.

One workaround would be to instead use a Java 8 lambda, but that's just a hack. The issue here is that Guava is still using a deprecated class in its own code.

The other workaround would be to just disallow the specific (functional) method instead of the whole class.

**Comment by uschindler** [comment]
A lambda would have same issue, as the `lambda$XY` method would also take ByteSource. So my only suggestion is to only disallow the method not the whole functional interface.

**Comment by uschindler** [comment]
BTW: When building your project on Windows (which I do), CheckStyle complains about missing line endings at end of files. Maybe an issue with windows CRLF vs. LF. I am using LF in my Git config, no CRLF. I disabled CheckStyle when building, with `phase=none`.

**Comment by leventov** [comment]
@uschindler thanks, forbidding interface methods looks like the most reasonable solution.
