### ISSUE TITLE
Gradle: SourceSets added after plugin loading don't get tasks

### ISSUE THREAD

**Issue by uschindler** [policeman-tools/forbidden-apis#138]
I found this by testing Elasticsearch. ES adds a sourceset named "java9", but this does not get tasks setup, so a task named `forbiddenApisJava9` is missing.

The reason is that at the time the plugin is applied, the additional sourcesets are not yet defined. Instead of using the standard `collect` groovy closure, it should use `all`, which applies a closure to already existing and later added sourcesets: [all method of DomainObjectCollection](https://docs.gradle.org/current/javadoc/org/gradle/api/DomainObjectCollection.html#all-groovy.lang.Closure-)

**Comment by uschindler** [comment]
Here is the PR: #139 

@rjernst: do you think this is OK?

**Comment by karussell** [comment]
We are currently trying out jdk10 https://github.com/graphhopper/graphhopper/pull/1327 with forbiddenapis and have a problem there:

Parsing signatures failed: Invalid bundled signature reference (JDK version is invalid): jdk-unsafe-1.10

See https://travis-ci.org/graphhopper/graphhopper/jobs/378749464

Is this a different issue or something because we are using unsafe?

**Comment by uschindler** [comment]
This has nothing to do with this. Update forbidden-apis and specify as "10" not "1.10". The latter is no valid java version.

**Comment by karussell** [comment]
Cool. Working now. Thanks a lot! And thanks for your work on this tool!
