### ISSUE TITLE
maven install on calcite generated this error

### ISSUE THREAD

**Issue by AsmaZgo** [policeman-tools/forbidden-apis#149]
[ERROR] Failed to execute goal de.thetaphi:forbiddenapis:2.3:check (default) on project .  : IO problem while reading files with API signatures. /../src/main/config/forbidden-apis/signatures.txt (No such file or directory) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by uschindler** [comment]
Hi,
the error message says explicitely whats wrong. According to maven guidelines, relative paths should be avoided and variables/properties be used. I am not sure what you are tyring to do. A path starting with "/.." seems wrong anyways.
There is nothing special in forbiddenapis, this is all handled by Maven, forbiddenapis just gets a "File" instance pointing to the signatures file. If you see a problem with that behaviour, open an issue in Maven.
Uwe

**Comment by uschindler** [comment]
Please report this issue at Apache Calcite. I quickly checked what Apache Calcite is doing. It looks correct there. I have the feeling the issue comes form the fact that "top.dir" property is incorrectly configured. I have no idea how the build of calcite is structured, but maybe you cant build subprojects without executing main build.

I will close this issue.
