### ISSUE TITLE
PGP key used for POM cannot be verified

### ISSUE THREAD

**Issue by sdavids** [policeman-tools/forbidden-apis#156]
https://docs.gradle.org/6.2/userguide/dependency_verification.html

build.gradle

```
plugins {
  id 'de.thetaphi.forbiddenapis' version '2.7'
}

wrapper.configure {
  gradleVersion = '6.2.1'
}
```

Execute:

```
$ ./gradlew --write-verification-metadata pgp,sha256 help
...
A verification file was generated but some problems were discovered:
   - some artifacts aren't signed or the signature couldn't be retrieved.
   - some signature verification failed. Checksums were generated for those artifacts but you MUST check if there's an actual problem. Look for entries with the following comment: PGP verification failed
```

`gradle/verification-metadata.xml` will now have the following entry:

```
      <component group="de.thetaphi" name="forbiddenapis" version="2.7">
...
         <artifact name="forbiddenapis-2.7.pom">
            <ignored-keys>
               <ignored-key id="0186f8b24c5bc02c94a0e0e486f75e83e1ee085f" reason="PGP verification failed"/>
            </ignored-keys>
            <sha256 value="aab54d67ee6c7e23c8fc98f7477621bac2742991a3ca00c5ee0625ecf0e136fe" origin="Generated by Gradle because PGP signature verification failed!"/>
         </artifact>
      </component>
```

**Comment by uschindler** [comment]
The key is on public keyservers, please install it in your local gpg: http://keys.gnupg.net/pks/lookup?op=get&search=0x86F75E83E1EE085F

Without signing artifacts correctly, they can't be upoaded to Sonatype's repository.

**Comment by uschindler** [comment]
FYI, The GPG keservers are sometimes returning errors (Like HTTP error 504, Gateway timeout), maybe Gradle wasn't able to download it.

**Comment by sdavids** [comment]
This is still happening:

```
      <component group="de.thetaphi" name="forbiddenapis" version="3.1">
         <artifact name="forbiddenapis-3.1.jar">
            <pgp value="0186f8b24c5bc02c94a0e0e486f75e83e1ee085f"/>
         </artifact>
         <artifact name="forbiddenapis-3.1.pom">
            <ignored-keys>
               <ignored-key id="0186f8b24c5bc02c94a0e0e486f75e83e1ee085f" reason="PGP verification failed"/>
            </ignored-keys>
            <sha256 value="f7eb8518766237006e3e3307f4c45230a8796c439efc900ce92d622757f2c263" origin="Generated by Gradle because PGP signature verification failed!"/>
         </artifact>
      </component>
      <component group="de.thetaphi.forbiddenapis" name="de.thetaphi.forbiddenapis.gradle.plugin" version="3.1">
         <artifact name="de.thetaphi.forbiddenapis.gradle.plugin-3.1.pom">
            <sha256 value="f828f697a64060f2d3579fd2978c120ea31d9762ecb907d59a1d91e13a578705" origin="Generated by Gradle because artifact wasn't signed"/>
         </artifact>
      </component>
```

**Comment by uschindler** [comment]
Hi,

the plugin is signed on Maven central. If you use the approach with the Gradle Plugin directive (not as build-dependencies), Gradle uses its own Plugin Portal, where the Artifacts are cloned for convenience reasons.

The deployment in the Gradle Plugin Portal is a hack (because the plugin can't use Gradle to build itsself), so basically the artifacts are copied from Maven Central to the Plugin portal using the plugin-plugin and a separate, automatically generated, Maven POM is added. I have no idea how to sign this - and I don't know how to carry over the signatures from Maven Central. In addition, I refuse to sign a POM file that I have not created on my own but are generated by the Gradle Plugin Portal on deployment. So IMHO, it's the plugin's portal to sign its auto-generated POM file, as it is not content I created.

So I'd suggest that you just include the plugin using the "old" way using build-dependencies and `apply plugin`. Then you can be sure that you get the originals, which are signed.

The code for the *optional* deployment for convenience on the Gradle Plugin Portal. I just use it, but have no idea how to tell the plugin portal to sign ts own shit: https://github.com/policeman-tools/forbidden-apis/tree/master/src/tools/gradle-plugin-portal

**Comment by sdavids** [comment]
https://github.com/gradle/gradle/issues/15441

**Comment by uschindler** [comment]
Thanks. That's helpful.
