### ISSUE TITLE
Bundled signatures not found: jdk-unsafe-16

### ISSUE THREAD

**Issue by bmarwell** [policeman-tools/forbidden-apis#176]
Hi,

I think the issue title describes it well :)

**Comment by uschindler** [comment]
Jdk 16 is not yet released. Signatures for forbidden apis coming later, as the official API is not yet released.

**Comment by uschindler** [comment]
If you want to use preview releases, separately setup the version for unsafe, deprecated,... Signatures using the target version parameter.

**Comment by bmarwell** [comment]
> Jdk 16 is not yet released

So? You could probably already support it as best as possible anyway.

> If you want to use preview releases, separately setup the version for unsafe, deprecated,... Signatures using the target version parameter.

I use `*-15` for now.

**Comment by uschindler** [comment]
bq. So? You could probably already support it as best as possible anyway.

Forbiddenapis is quite mature and the release cycle is (due to lack of time) only half-yearly. So a new version mostly comes out when a new Java version comes out.

Nevertheless, the jdk-unsafe signatures don't change much anymore, so new versions more or less only copy old versions (it includes previous signatures file). This won't work for jdk-deprecated and other ones taking verison numbers, as those are autogenerated from JDK release artifacts. This could be done earlier, but is still a chicken-egg problem. With a new version, we also upgrade ASM to latest version and because the class file format may also change, it's a bit of risk to support something in flux.

Because of this reasons, no official support will be added.

My personal opinion: Why would anybody in a serious project compile with flag `--release 16` or maybe without a version switch at all (unless it's a game project)? Forbiddenapis "targetVersion" (also possible as "releaseVersion" since 3.1 with Maven, see https://github.com/policeman-tools/forbidden-apis/commit/6b7b8d7edcb81fd6e3d1e406baf43de524e57cfa) should be the same as javac's release switch. Projects explicitely targetting JDK 16 are special, those can use workarounds like specifying a different targetVersion from javac's.

**Comment by uschindler** [comment]
A small addition: I had some plans to add support to auto-fallback to previous versions for signatures starting with "jdk-", while printing a realling big warning. It was just not yet implemented and based on other stuff going wrong easily, this is problematic - for the reasons listed before.

**Comment by uschindler** [comment]
Fixed through ac754c4bbc5e3e2a988dd266845e8ff3622781b1
