### ISSUE TITLE
Ignoring unresolvable signatures in existing classes

### ISSUE THREAD

**Issue by yrodiere** [policeman-tools/forbidden-apis#197]
## Requested feature

The [ignoreSignaturesOfMissingClasses](https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/check-mojo.html#ignoreSignaturesOfMissingClasses) setting makes ForbiddenAPIs ignore signatures if it cannot find the corresponding class.

I would like to add another setting that makes ForbiddenAPIs ignore signatures that it cannot find in *existing* classes, e.g. removed methods.

## Use case

In Hibernate Search, we compile with JDK 11 (still), but we want to avoid signatures deemed dangerous even in later JDKs. For example a method could be fine with JDK11, but deprecated in JDK17.

Just forbidding `jdk-deprecated-1.8` wouldn't protect us from using that method, so we actually list signatures of all JDKs we want to support:

```
                                    <bundledSignature>jdk-unsafe-1.8</bundledSignature>
                                    <bundledSignature>jdk-unsafe-9</bundledSignature>
                                    <bundledSignature>jdk-unsafe-10</bundledSignature>
                                    <bundledSignature>jdk-unsafe-11</bundledSignature>
                                    <bundledSignature>jdk-unsafe-12</bundledSignature>
                                    <bundledSignature>jdk-unsafe-13</bundledSignature>
                                    <bundledSignature>jdk-unsafe-14</bundledSignature>
                                    <bundledSignature>jdk-unsafe-15</bundledSignature>
                                    <bundledSignature>jdk-unsafe-16</bundledSignature>
                                    <bundledSignature>jdk-unsafe-17</bundledSignature>

                                    <bundledSignature>jdk-deprecated-1.8</bundledSignature>
                                    <bundledSignature>jdk-deprecated-9</bundledSignature>
                                    <bundledSignature>jdk-deprecated-10</bundledSignature>
                                    <bundledSignature>jdk-deprecated-11</bundledSignature>
                                    <bundledSignature>jdk-deprecated-12</bundledSignature>
                                    <bundledSignature>jdk-deprecated-13</bundledSignature>
                                    <bundledSignature>jdk-deprecated-14</bundledSignature>
                                    <bundledSignature>jdk-deprecated-15</bundledSignature>
                                    <bundledSignature>jdk-deprecated-16</bundledSignature>
                                    <bundledSignature>jdk-deprecated-17</bundledSignature>

                                    <bundledSignature>jdk-internal-1.8</bundledSignature>
                                    <bundledSignature>jdk-internal-9</bundledSignature>
                                    <bundledSignature>jdk-internal-10</bundledSignature>
                                    <bundledSignature>jdk-internal-11</bundledSignature>
                                    <bundledSignature>jdk-internal-12</bundledSignature>
                                    <bundledSignature>jdk-internal-13</bundledSignature>
                                    <bundledSignature>jdk-internal-14</bundledSignature>
                                    <bundledSignature>jdk-internal-15</bundledSignature>
                                    <bundledSignature>jdk-internal-16</bundledSignature>
                                    <bundledSignature>jdk-internal-17</bundledSignature>
```

See https://github.com/hibernate/hibernate-search/blob/4f1b62ff1d69c713d3bbf043e76a1d633be88bb3/pom.xml#L1837-L1868

This used to work fine until recently, when the signature `java.text.NumberFormat#getCompactNumberInstance()` was introduced in `jdk-unsafe-something` (17, maybe?). That method doesn't exist in JDK 11, and thus ForbiddenAPIs fails with this error:

```
[ERROR] Failed to execute goal de.thetaphi:forbiddenapis:3.3:check (verify-forbidden-apis) on project hibernate-search-util-common: Parsing signatures failed: Method not found while parsing signature: java.text.NumberFormat#getCompactNumberInstance() -> [Help 1]
```

Since `NumberFormat` does exist in JDK11, enabling `ignoreSignaturesOfMissingClasses` isn't useful here. In order to make this work, we would really need to make ForbiddenAPIs ignore a missing signature in an *existing* class.

## API suggestions

We could add a `true`/`false` setting named `igoreAllMissingSignatures`, similar to [ignoreSignaturesOfMissingClasses](https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/check-mojo.html#ignoreSignaturesOfMissingClasses), but with broader effect.

Of course, with this setting enabled, people would run the risk of putting invalid signatures in their signature files (e.g. a typo), and never noticing that their signature file has no effect, since the signature is not found. I imagine that's the reason [failOnUnresolvableSignatures](https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/check-mojo.html#failOnUnresolvableSignatures) was deprecated?

A perhaps safer solution could just be a class/package filter, e.g. `ignoreMissingSignatures=java.**`, so that only missing signatures in specific packages are ignored.

Alternatively, we could use a signature bundle filter, e.g. `ignoreMissingSignatures=jdk-deprecated-*`, to state that all signatures in a matching signature bundle are trusted to be correct and that missing signatures are just a result of JDK mismatch.

**Comment by yrodiere** [comment]
Hey @uschindler , I can submit a PR for this new setting if you want, but could you confirm you agree with one of the proposed solutions first? Thanks!

**Comment by uschindler** [comment]
Hey,
about "deprecated" stuff there is no problem at moment, I'd suggest to do the following:

1. `jdk-unsafe` signatures: use the version as your compile target (thats automatically handled thorugh the maven property)
2. `jdk-deprecated`: here you can use the Java 17 one easily because there is a special case: The signatures files for deprecated signatures are autogenerated (so we know they have no typos). Becaus eof this and because deprecated methods may be removed in future, those signatures files automatically ignore all missing signatures (see the `@ignoreUnresolvable` at beginning of file: https://github.com/policeman-tools/forbidden-apis/blob/main/src/main/resources/de/thetaphi/forbiddenapis/signatures/jdk-deprecated-17.txt#L7). So you can load the 17 ones easily. But keep in mind, the 17 files already contains less forbidden apis than the 11 one, if methods were ignored. So for full checking do the following: Load the default 11 signatures and the 17 ones, too)

Number 2 you already do for all signatures. But you should only do this for the deprecated ones. For unsafe it makes no sense at all, because code compiled against java 11 cannot contain those signatures.

So my suggestion:
- have a list of *all* `jdk-deprecated` signatures (this should work because it ignores missing ones)
- for `jdk-unsafe` only use the version that you compile against. Using later versions brings no added benefit.
- `jdk-internal` is not recommended anymore (not yet deprecated), I'd use  `jdk-non-portable`, which is dynamic. But there is no risk in listing all of them, as those are package-level signatures anyways.

I see no reason for adding another setting like proposed. This has nothing to do with the current problem. It might be helpful for your own signatures files (which is a different issue).

**Comment by uschindler** [comment]
You patch in related Hibernate issue looks fine. There is no reason to list all jdk-unsafe ones because they include each other.

In the future there may be some tricks needed when JDK indeed deprecates and removes methods marked as unsafe. But my plan here is to make sure that all signatures files are tested throughly and the `@ignoreUnresolvable` gets applied dynamically.

At some point in the future I may merge all signatures for unsafe and deprecated into one which is tested throughly using different JDKS for missing ones and no longer supply per-version ones.

**Comment by uschindler** [comment]
See also #196.

**Comment by uschindler** [comment]
> I imagine that's the reason [failOnUnresolvableSignatures](https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/check-mojo.html#failOnUnresolvableSignatures) was deprecated?

Exactly.

**Comment by yrodiere** [comment]
> For unsafe it makes no sense at all, because code compiled against java 11 cannot contain those signatures.

I suppose it could make sense if a signature was safe in JDK 11 but not in JDK 17; we're seeing changes of default encoding in recent JDKs, for example, so I can imagine a method could become unsafe if the default encoding used in that method changed.

But you're right, it's probably not the case at the moment, so referencing all `jdk-unsafe` bundles is not currently useful.

I didn't know about `@ignoreUnresolvable`. Thanks for mentioning that.

In any case, thanks for the explanation, I'll do as you suggested.

**Comment by uschindler** [comment]
> I suppose it could make sense if a signature was safe in JDK 11 but not in JDK 17; we're seeing changes of default encoding in recent JDKs, for example, so I can imagine a method could become unsafe if the default encoding used in that method changed.

Using UTF-8 as default in JDK 18 does *not* remove the "unsafe" problem. The change in 18 just changes the default to 18. But anybody calling `Charset#setDefault()` will change that default and all code without explicit charset will be unsafe again. So the JDK-18 changes don't bring anything as it is only a change of default. The problem still persists.

**Comment by yrodiere** [comment]
Right, that was a bad example. I simply meant that a method could change behavior and thus become unsafe. But as I said I don't have an actual example of that currently (and I don't think there is one), so I'm just making useless noise at this point :grin:
