### ISSUE TITLE
Require at least Maven 3.2.5

### ISSUE THREAD

**Issue by bmarwell** [policeman-tools/forbidden-apis#236]
All official and mojohaus plugins have migrated to v3.2.5 because of outstanding dependency issues. It would be great if this plugin would require Maven 3.2.5 for the same reason. This would also bring Maven 4 compatibility.

However, Maven 3.2.x requires at least Java 6, while 3.1.x is still on 5. But then, I have no pity for anyone updating a plugin to a 2023 version but still wanting to do a build with Java 5. You can do it with toolchains if you really need to.

**Comment by uschindler** [comment]
Hi,
Actually the plugin does not depend on any maven version, so there are no dependency problems. The plugin does not depend on anything at all (self contained jar):

https://central.sonatype.com/artifact/de.thetaphi/forbiddenapis/3.6/dependencies

The minimum version is just the one that is required because of required APIs provided not before this Maven version. But this limitation does not affect maven dependency resolution at all.

So I don't know what you want to change.

**Comment by uschindler** [comment]
Here is the pom: https://repo1.maven.org/maven2/de/thetaphi/forbiddenapis/3.6/forbiddenapis-3.6.pom

**Comment by bmarwell** [comment]
Thanks for the info.
